/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JAVAproject;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author ANUSHEEL
 */
public class Updatestations extends javax.swing.JFrame {
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    /**
     * Creates new form Updatestaions
     */
    public Updatestations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        StncodeTF = new javax.swing.JTextField();
        SnameTF = new javax.swing.JTextField();
        CategoryTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ZoneTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Division = new javax.swing.JTextField();
        updBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loadBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        RemarksTF = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        intBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Division");

        SnameTF.setEnabled(false);

        CategoryTF.setEnabled(false);

        jLabel4.setText("Zone");

        ZoneTF.setEnabled(false);

        jLabel3.setText("Category");

        Division.setEnabled(false);

        updBtn.setText("Update Record");
        updBtn.setEnabled(false);
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Delete Records");
        delBtn.setEnabled(false);
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Sname");

        jLabel1.setText("Stn_code");

        loadBtn.setText("Load Record");
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Remarks");

        RemarksTF.setEnabled(false);

        jButton2.setText("Disable");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Enable");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        intBtn.setText("Insert Record");
        intBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intBtnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Andalus", 3, 36)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JAVAproject/irctc_logo_en_IN.gif.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(updBtn)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Division, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ZoneTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CategoryTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StncodeTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SnameTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RemarksTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(intBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(loadBtn)
                                            .addComponent(jButton2)
                                            .addComponent(jButton1))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(StncodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(SnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CategoryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ZoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(RemarksTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadBtn)
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(82, 82, 82)
                                .addComponent(intBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updBtn)
                    .addComponent(delBtn))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed

        int ans = JOptionPane.showConfirmDialog(null, "Surely wanna update the Record?");
        if(ans==JOptionPane.YES_OPTION){
            try{
                stmt = con.createStatement();
                String query = "UPDATE stations SET Sname = \"" + SnameTF.getText()+"\", Category = \"" + CategoryTF.getText() + "\" , zone = \"" + ZoneTF.getText() + "\" ,division = \"" +Division.getText() +"\" , remarks = \""+ RemarksTF.getText()+"\" WHERE stn_code = \"" + StncodeTF.getText() + "\";";
                stmt.execute(query);
                JOptionPane.showMessageDialog(null, "Record successfully updated.");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.toString());
            }
            StncodeTF.setText("");
            SnameTF.setText("");
            CategoryTF.setText("");
            ZoneTF.setText("");
            Division.setText("");
            RemarksTF.setText("");
            updBtn.setEnabled(false);
            delBtn.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_updBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed

        int res = JOptionPane.showConfirmDialog(null, "Wanna delete the record for sure?");
        if(res == JOptionPane.YES_OPTION){
            try{
                stmt = con.createStatement();
                String query = "DELETE FROM stations WHERE stn_code = \"" + StncodeTF.getText() + "\" ;";
                stmt.execute(query);
                JOptionPane.showMessageDialog(null, "Record Deleted!");
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
        StncodeTF.setText("");
        SnameTF.setText("");
        CategoryTF.setText("");
        ZoneTF.setText("");
        Division.setText("");
        RemarksTF.setText("");
        updBtn.setEnabled(false);
        delBtn.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_delBtnActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed

        try{
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/irctc","root","ap");
            stmt = con.createStatement();
            String query = "SELECT * from stations WHERE stn_code = \"" + StncodeTF.getText() + "\";";
            rs = stmt.executeQuery(query);
            if (rs.next()){
                String un = rs.getString("stn_code");
                String pass = rs.getString("Sname");
                String cate = rs.getString("Category");
                String div = rs.getString("Division");
                String zone = rs.getString("zone");
                String remarks = rs.getString("remarks");
                SnameTF.setText(pass);
                CategoryTF.setText(cate);
                ZoneTF.setText(div);
                Division.setText(zone);
                RemarksTF.setText(remarks);
                updBtn.setEnabled(true);
                delBtn.setEnabled(true);
                SnameTF.setEnabled(true);
                CategoryTF.setEnabled(true);
                ZoneTF.setEnabled(true);
                Division.setEnabled(true);
                RemarksTF.setEnabled(true);
            } else{
                JOptionPane.showMessageDialog(null,"No Such Record Found.");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString() );
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_loadBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SnameTF.setEnabled(false);
        CategoryTF.setEnabled(false);
        ZoneTF.setEnabled(false);
        Division.setEnabled(false);
        RemarksTF.setEnabled(false);
        loadBtn.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        SnameTF.setEnabled(true);
        CategoryTF.setEnabled(true);
        ZoneTF.setEnabled(true);
        Division.setEnabled(true);
        RemarksTF.setEnabled(true);
        loadBtn.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void intBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intBtnActionPerformed
        Connection con;
        Statement stmt;
        try{
            Class.forName("java.sql.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost/irctc","root","ap");
            stmt=con.createStatement();
            stmt=con.createStatement();
            String query = "INSERT INTO CUSTOMER " +
            "VALUES ("+StncodeTF.getText()+",'"+SnameTF.getText()+"','"+CategoryTF.getText()+"','"+ZoneTF.getText()+"','"+Division.getText()+"','"+RemarksTF.getText()+"');";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Record successfully inserted");

            SnameTF.setText("");
            StncodeTF.setText("");
            CategoryTF.setText("");
            ZoneTF.setText("");
            Division.setText("");
            RemarksTF.setText("");

        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_intBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updatestations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updatestations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updatestations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updatestations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updatestations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CategoryTF;
    private javax.swing.JTextField Division;
    private javax.swing.JTextField RemarksTF;
    private javax.swing.JTextField SnameTF;
    private javax.swing.JTextField StncodeTF;
    private javax.swing.JTextField ZoneTF;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton intBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loadBtn;
    private javax.swing.JButton updBtn;
    // End of variables declaration//GEN-END:variables
}
