/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Updateuser.java
 *
 * Created on Nov 2, 2016, 9:32:15 AM
 */

package JAVAproject;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author admin
 */
public class Updateusers extends javax.swing.JFrame {

    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;

    /** Creates new form Updateusers */
    public Updateusers() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JTextField();
        categoryTF = new javax.swing.JTextField();
        loadBtn = new javax.swing.JButton();
        updBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        remarksTF = new javax.swing.JTextField();
        disableBtn = new javax.swing.JButton();
        enableBtn = new javax.swing.JButton();
        intBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Loginbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setText("Category");

        passwordTF.setEnabled(false);

        categoryTF.setEnabled(false);

        loadBtn.setText("Load Record");
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        updBtn.setText("Update Record");
        updBtn.setEnabled(false);
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Delete Records");
        delBtn.setEnabled(false);
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Remarks");

        remarksTF.setEnabled(false);

        disableBtn.setText("Disable");
        disableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableBtnActionPerformed(evt);
            }
        });

        enableBtn.setText("Enable");
        enableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableBtnActionPerformed(evt);
            }
        });

        intBtn.setText("Insert Record");
        intBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intBtnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Andalus", 3, 36)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JAVAproject/irctc_logo_en_IN.gif.gif"))); // NOI18N

        Loginbtn.setText("Go to Login");
        Loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadBtn)
                    .addComponent(disableBtn)
                    .addComponent(enableBtn)
                    .addComponent(intBtn))
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(116, 116, 116)
                                    .addComponent(remarksTF))
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(categoryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(109, 109, 109)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(usernameTF)
                                            .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updBtn)
                                .addGap(67, 67, 67)
                                .addComponent(delBtn)))
                        .addGap(97, 97, 97)
                        .addComponent(Loginbtn)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadBtn)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(disableBtn))
                            .addComponent(enableBtn))
                        .addGap(34, 34, 34)
                        .addComponent(intBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(categoryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(remarksTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updBtn)
                    .addComponent(delBtn)
                    .addComponent(Loginbtn))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed

        try{
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/irctc","root","ap");
            stmt = con.createStatement();
            String query = "SELECT * from users WHERE username = \"" + usernameTF.getText() + "\";";
            rs = stmt.executeQuery(query);
            if (rs.next()){
                String un = rs.getString("username");
                String pass = rs.getString("password");
                String cate = rs.getString("category");
                String remarks = rs.getString("remarks");
                passwordTF.setText(pass);
                categoryTF.setText(cate);
                remarksTF.setText(remarks);
                updBtn.setEnabled(true);
                delBtn.setEnabled(true);
                passwordTF.setEnabled(true);
                categoryTF.setEnabled(true);
                remarksTF.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"No Such Record Found.");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString() );
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_loadBtnActionPerformed

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed

        int ans = JOptionPane.showConfirmDialog(null, "Surely wanna update the Record?");
        if(ans==JOptionPane.YES_OPTION){
            try{
                stmt = con.createStatement();
                String query = "UPDATE users SET password = \"" + passwordTF.getText()+"\", category = \"" + categoryTF.getText() + "\", remarks = \"" + remarksTF.getText() + "\" WHERE username = \"" + usernameTF.getText() + "\"";
                stmt.execute(query);
                JOptionPane.showMessageDialog(null, "Record successfully updated.");
            }catch(Exception e){
                JOptionPane.showConfirmDialog(null, e.toString());
            }
        usernameTF.setText("");
        passwordTF.setText("");
        categoryTF.setText("");
        remarksTF.setText("");
        updBtn.setEnabled(false);
        delBtn.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_updBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed

    int res = JOptionPane.showConfirmDialog(null, "Wanna delete the record for sure?");
    if(res == JOptionPane.YES_OPTION){
        try{
            stmt = con.createStatement();
            String query = "DELETE FROM dept WHERE username = \"" + usernameTF.getText() + "\" ;";
            stmt.execute(query);
            JOptionPane.showMessageDialog(null, "Record Deleted!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    usernameTF.setText("");
    passwordTF.setText("");
    categoryTF.setText("");
    remarksTF.setText("");
    updBtn.setEnabled(false);
    delBtn.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_delBtnActionPerformed

    private void disableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableBtnActionPerformed
        
        passwordTF.setEnabled(false);
        categoryTF.setEnabled(false);
        remarksTF.setEnabled(false);
        loadBtn.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_disableBtnActionPerformed

    private void enableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableBtnActionPerformed

        
        passwordTF.setEnabled(true);
        categoryTF.setEnabled(true);
        remarksTF.setEnabled(true);
        loadBtn.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_enableBtnActionPerformed

    private void intBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intBtnActionPerformed
        Connection con;
        Statement stmt;
        try{
            Class.forName("java.sql.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost/irctc","root","ap");
            stmt=con.createStatement();
            stmt=con.createStatement();
            String query = "INSERT INTO CUSTOMER " +
            "VALUES ("+usernameTF.getText()+",'"+passwordTF.getText()+"','"+categoryTF.getText()+"','"+remarksTF.getText()+"');";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Record successfully inserted");

            usernameTF.setText("");
            passwordTF.setText("");
            categoryTF.setText("");
            remarksTF.setText("");

        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_intBtnActionPerformed

    private void LoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnActionPerformed

    LoginForm oo = new LoginForm();
    oo.setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginbtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updateusers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loginbtn;
    private javax.swing.JTextField categoryTF;
    javax.swing.JButton delBtn;
    javax.swing.JButton disableBtn;
    javax.swing.JButton enableBtn;
    private javax.swing.JButton intBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    javax.swing.JButton loadBtn;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JTextField remarksTF;
    javax.swing.JButton updBtn;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables

}
