/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Updatetrains.java
 *
 * Created on Nov 4, 2016, 8:21:02 AM
 */

package JAVAproject;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author User8
 */
public class Updatetrains extends javax.swing.JFrame {
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    /** Creates new form Updatetrains */
    public Updatetrains() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        updBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loadBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Train_noTF = new javax.swing.JTextField();
        TnameTF = new javax.swing.JTextField();
        TypeTF = new javax.swing.JTextField();
        MaxsTF = new javax.swing.JTextField();
        CommTF = new javax.swing.JTextField();
        intBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Maxseats");

        jLabel3.setText("Type");

        updBtn.setText("Update Record");
        updBtn.setEnabled(false);
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Delete Records");
        delBtn.setEnabled(false);
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Tname");

        jLabel1.setText("Train no");

        loadBtn.setText("Load Record");
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Comments");

        TnameTF.setEnabled(false);

        TypeTF.setEnabled(false);

        MaxsTF.setEnabled(false);

        CommTF.setEnabled(false);

        intBtn.setText("Insert Record");
        intBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Disable");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Enable");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Andalus", 3, 36)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JAVAproject/irctc_logo_en_IN.gif.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(MaxsTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TypeTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Train_noTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TnameTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(loadBtn)
                            .addComponent(jButton2)
                            .addComponent(intBtn))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updBtn)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(delBtn)
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(CommTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel13)
                .addGap(0, 174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel13)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Train_noTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(MaxsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addComponent(loadBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CommTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updBtn)
                    .addComponent(delBtn))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed

        int ans = JOptionPane.showConfirmDialog(null, "Surely wanna update the Record?");
        if(ans==JOptionPane.YES_OPTION){
            try{
                stmt = con.createStatement();
                String query = "UPDATE trains SET Tname = \"" + TnameTF.getText()+"\", Type = \"" + TypeTF.getText() + "\" , maxseats = \"" + MaxsTF.getText() + " \" ,comments = \"" +CommTF.getText() + "\" WHERE train_no = \"" + Train_noTF.getText() + "\";";
                stmt.execute(query);
                JOptionPane.showMessageDialog(null, "Record successfully updated.");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.toString());
            }
            Train_noTF.setText("");
            TnameTF.setText("");
            TypeTF.setText("");
            MaxsTF.setText("");
            CommTF.setText("");
            updBtn.setEnabled(false);
            delBtn.setEnabled(false);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_updBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed

        int res = JOptionPane.showConfirmDialog(null, "Wanna delete the record for sure?");
        if(res == JOptionPane.YES_OPTION){
            try{
                stmt = con.createStatement();
                String query = "DELETE FROM trains WHERE Train_no = \"" + Train_noTF.getText() + "\" ;";
                stmt.execute(query);
                JOptionPane.showMessageDialog(null, "Record Deleted!");
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
        Train_noTF.setText("");
        TnameTF.setText("");
        TypeTF.setText("");
        MaxsTF.setText("");
        CommTF.setText("");
        updBtn.setEnabled(false);
        delBtn.setEnabled(false);
        // TODO add your handling code here:
}//GEN-LAST:event_delBtnActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed

        try{
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/irctc","root","ap");
            stmt = con.createStatement();
            String query = "SELECT * from trains WHERE Train_no = \"" + Train_noTF.getText() + "\";";
            rs = stmt.executeQuery(query);
            if (rs.next()){
                String un = rs.getString("Train_no");
                String pass = rs.getString("Tname");
                String cate = rs.getString("Type");
                String maxs = rs.getString("Maxseats");
                String comments = rs.getString("comments");
                TnameTF.setText(pass);
                TypeTF.setText(cate);
                MaxsTF.setText(maxs);
                CommTF.setText(comments);
                updBtn.setEnabled(true);
                delBtn.setEnabled(true);
                TnameTF.setEnabled(true);
                TypeTF.setEnabled(true);
                MaxsTF.setEnabled(true);
                CommTF.setEnabled(true);
            } else{
                JOptionPane.showMessageDialog(null,"No Such Record Found.");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString() );
        }
        // TODO add your handling code here:
}//GEN-LAST:event_loadBtnActionPerformed

    private void intBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intBtnActionPerformed
        Connection con;
        Statement stmt;
        try{
            Class.forName("java.sql.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost/irctc","root","ap");
            stmt=con.createStatement();
            stmt=con.createStatement();
            String query = "INSERT INTO CUSTOMER " +
            "VALUES ("+Train_noTF.getText()+",'"+TnameTF.getText()+"','"+TypeTF.getText()+"','"+MaxsTF.getText()+"','"+CommTF.getText()+"');";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Record successfully inserted");

            Train_noTF.setText("");
            TnameTF.setText("");
            TypeTF.setText("");
            MaxsTF.setText("");
            CommTF.setText("");

        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_intBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TnameTF.setEnabled(false);
        TypeTF.setEnabled(false);
        MaxsTF.setEnabled(false);
        CommTF.setEnabled(false);
        loadBtn.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        TnameTF.setEnabled(true);
        TypeTF.setEnabled(true);
        MaxsTF.setEnabled(true);
        CommTF.setEnabled(true);
        loadBtn.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updatetrains().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CommTF;
    private javax.swing.JTextField MaxsTF;
    private javax.swing.JTextField TnameTF;
    private javax.swing.JTextField Train_noTF;
    private javax.swing.JTextField TypeTF;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton intBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loadBtn;
    private javax.swing.JButton updBtn;
    // End of variables declaration//GEN-END:variables

}
