/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JAVAproject;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author User3
 */
public class Updateschedule extends javax.swing.JFrame {
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    /**
     * Creates new form Updateschedule
     */
    public Updateschedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loadBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        QuotaTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FTrainTF = new javax.swing.JTextField();
        FStnTF = new javax.swing.JTextField();
        ArrivalTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DepartureTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DaysTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        intBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        updBtn.setText("Update Record");
        updBtn.setEnabled(false);
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Delete Records");
        delBtn.setEnabled(false);
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Fstn_code");

        jLabel1.setText("FTrain_no");

        loadBtn.setText("Load Record");
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Quota");

        QuotaTF.setEnabled(false);

        jLabel5.setText("Days");

        FStnTF.setEnabled(false);

        ArrivalTF.setEnabled(false);

        jLabel4.setText("Departure");

        DepartureTF.setEnabled(false);

        jLabel3.setText("Arrival");

        DaysTF.setEnabled(false);

        jButton1.setText("Enable");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        intBtn.setText("Insert Record");
        intBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Disable");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Andalus", 3, 36)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JAVAproject/irctc_logo_en_IN.gif.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(updBtn)
                .addGap(186, 186, 186)
                .addComponent(delBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addGap(162, 162, 162)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FStnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FTrainTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ArrivalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DepartureTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DaysTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuotaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1)
                                    .addComponent(loadBtn)
                                    .addComponent(intBtn))))
                        .addGap(114, 114, 114))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(FTrainTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(FStnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ArrivalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(DepartureTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(DaysTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(QuotaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadBtn)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jButton2))
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updBtn)
                    .addComponent(delBtn))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed

        int ans = JOptionPane.showConfirmDialog(null, "Surely wanna update the Record?");
        if(ans==JOptionPane.YES_OPTION){
            try{
                stmt = con.createStatement();
                String query = "UPDATE schedule SET FStn_code = \"" + FStnTF.getText()+"\", Arrival = \"" + ArrivalTF.getText() + "\" , departure = \"" + DepartureTF.getText() + "\" ,days = \"" +DaysTF.getText() +"\" , Quota = \""+ QuotaTF.getText()+"\" WHERE FTrain_no = \"" + FTrainTF.getText() + "\";";
                stmt.execute(query);
                JOptionPane.showMessageDialog(null, "Record successfully updated.");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.toString());
            }
            FTrainTF.setText("");
            FStnTF.setText("");
            ArrivalTF.setText("");
            DepartureTF.setText("");
            DaysTF.setText("");
            QuotaTF.setText("");
            updBtn.setEnabled(false);
            delBtn.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_updBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed

        int res = JOptionPane.showConfirmDialog(null, "Wanna delete the record for sure?");
        if(res == JOptionPane.YES_OPTION){
            try{
                stmt = con.createStatement();
                String query = "DELETE FROM schedule WHERE FTrain_no = \"" + FTrainTF.getText() + "\" ;";
                stmt.execute(query);
                JOptionPane.showMessageDialog(null, "Record Deleted!");
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
        FTrainTF.setText("");
        FStnTF.setText("");
        ArrivalTF.setText("");
        DepartureTF.setText("");
        DaysTF.setText("");
        QuotaTF.setText("");
        updBtn.setEnabled(false);
        delBtn.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_delBtnActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed

        try{
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/irctc","root","ap");
            stmt = con.createStatement();
            String query = "SELECT * from schedule WHERE FTrain_no = \"" + FTrainTF.getText() + "\";";
            rs = stmt.executeQuery(query);
            if (rs.next()){
                String un = rs.getString("FTrain_no");
                String pass = rs.getString("FStn_code");
                String arr = rs.getString("Arrival");
                String days = rs.getString("Days");
                String departure = rs.getString("departure");
                String Quota = rs.getString("Quota");
                FStnTF.setText(pass);
                ArrivalTF.setText(arr);
                DepartureTF.setText(departure);
                DaysTF.setText(days);
                QuotaTF.setText(Quota);
                updBtn.setEnabled(true);
                delBtn.setEnabled(true);
                FStnTF.setEnabled(true);
                ArrivalTF.setEnabled(true);
                DepartureTF.setEnabled(true);
                DaysTF.setEnabled(true);
                QuotaTF.setEnabled(true);
            } else{
                JOptionPane.showMessageDialog(null,"No Such Record Found.");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString() );
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_loadBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ArrivalTF.setEnabled(true);
        DaysTF.setEnabled(true);
        DepartureTF.setEnabled(true);
        FStnTF.setEnabled(true);
        QuotaTF.setEnabled(true);
        loadBtn.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void intBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intBtnActionPerformed
        Connection con;
        Statement stmt;
        try{
            Class.forName("java.sql.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost/irctc","root","ap");
            stmt=con.createStatement();
            stmt=con.createStatement();
            String query = "INSERT INTO CUSTOMER " +
            "VALUES ("+FTrainTF.getText()+",'"+ArrivalTF.getText()+"','"+DaysTF.getText()+"','"+DepartureTF.getText()+"','"+FStnTF.getText()+"','"+QuotaTF.getText()+"');";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Record successfully inserted");

            FTrainTF.setText("");
            ArrivalTF.setText("");
            DaysTF.setText("");
            DepartureTF.setText("");
            FStnTF.setText("");

        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_intBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrivalTF.setEnabled(false);
        DaysTF.setEnabled(false);
        DepartureTF.setEnabled(false);
        FStnTF.setEnabled(false);
        QuotaTF.setEnabled(false);
        loadBtn.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updateschedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updateschedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updateschedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updateschedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updateschedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArrivalTF;
    private javax.swing.JTextField DaysTF;
    private javax.swing.JTextField DepartureTF;
    private javax.swing.JTextField FStnTF;
    private javax.swing.JTextField FTrainTF;
    private javax.swing.JTextField QuotaTF;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton intBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loadBtn;
    private javax.swing.JButton updBtn;
    // End of variables declaration//GEN-END:variables
}
